# Generated by Django 4.0.3 on 2022-04-07 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_decembers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Decembers',
        ),
    ]
