# Generated by Django 4.0.3 on 2022-04-07 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_additionaldata_members_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.additionaldata'),
        ),
    ]
