# Generated by Django 4.0.3 on 2022-04-07 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_members_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaldata',
            name='member_email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.additionaldata'),
        ),
    ]
