# Generated by Django 4.0.3 on 2022-04-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_additionaldata_member_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionaldata',
            old_name='member_email',
            new_name='email',
        ),
    ]
