# Generated by Django 4.0.3 on 2022-04-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_rename_member_email_additionaldata_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='email',
        ),
        migrations.DeleteModel(
            name='AdditionalData',
        ),
    ]
