# Generated by Django 4.0.3 on 2022-04-07 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_remove_members_email_delete_additionaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='members',
            name='member_age',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='members.memberage'),
        ),
    ]
