# Generated by Django 4.0.3 on 2022-04-07 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_memberage_members_member_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberAge',
            new_name='Age',
        ),
    ]
