# Generated by Django 4.0.3 on 2022-04-07 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_rename_memberage_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='age',
            old_name='age',
            new_name='member_age',
        ),
        migrations.RemoveField(
            model_name='members',
            name='member_age',
        ),
        migrations.AddField(
            model_name='members',
            name='age',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.age'),
        ),
    ]
