# Generated by Django 4.0.3 on 2022-04-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_rename_age_age_member_age_remove_members_member_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='age',
        ),
        migrations.DeleteModel(
            name='Age',
        ),
    ]
