# Generated by Django 4.0.3 on 2022-04-07 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_age_members_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='age',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.age'),
        ),
    ]
