# Generated by Django 4.0.3 on 2022-04-07 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_rename_members_member'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Members',
        ),
    ]
