# Generated by Django 4.0.3 on 2022-04-07 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_rename_member_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='age',
        ),
        migrations.DeleteModel(
            name='Age',
        ),
    ]
